/**
 * Helpers for the per-chart "导出 Python" feature. Each chart that
 * supports the export defines a small `emit*ToPython()` function in
 * its own directory which receives the live config + computed data
 * snapshots and returns a self-contained matplotlib script as a
 * string. The shared `<ConfigManager>` panel renders an "导出 Python"
 * button whenever a chart wires an emitter through `useEvalChartConfig`;
 * clicking the button hands the source string to `downloadPythonFile`,
 * which kicks off a normal `<a download>` flow without touching disk.
 *
 * The emitters are pure functions — they never read the DOM, never
 * touch React state, never call `localStorage`. That makes them
 * trivially unit-testable and lets future tooling (e.g. CLI export,
 * a "preview the script" panel) consume the same utility surface.
 */
import { useEffect, type MutableRefObject } from 'react';

/** Fired by `<ConfigManager>` when the user clicks "导出 Python". */
export type PythonEmitter = () => string;

/**
 * Stash the latest closure into a ref each render so a stable click
 * handler stored in the shared `<ConfigManager>` can read the freshest
 * snapshot lazily. Charts call this AFTER all `textOverrides.resolve`
 * + `useMemo` data computations so the captured closure sees fully
 * populated state. Defined here (next to `PythonEmitter`) rather than
 * exported from React so chart files can stick to one import line.
 */
export function useLatestPythonEmitter(
  ref: MutableRefObject<PythonEmitter | null>,
  factory: PythonEmitter,
): void {
  useEffect(() => {
    ref.current = factory;
  });
}

/**
 * Persist a generated Python script to the user's machine. Mirrors
 * the JSON download path inside `<ConfigManager>` so the look-and-
 * feel of the two buttons stays consistent: same prompt-less,
 * single-click download with no clipboard intermediate.
 */
export function downloadPythonFile(filename: string, source: string): void {
  const blob = new Blob([source], { type: 'text/x-python' });
  const url = URL.createObjectURL(blob);
  try {
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
  } finally {
    URL.revokeObjectURL(url);
  }
}

/**
 * Wrap a JavaScript string into a Python triple-quoted literal,
 * escaping the closing-triple-quote sequence so user-supplied label
 * strings cannot break out of the string. Used by emitters when they
 * paste user-edited titles / captions into the generated script.
 */
export function pyTripleQuote(s: string): string {
  return `"""${s.replace(/"""/g, '\\"\\"\\"')}"""`;
}

/**
 * Wrap a JavaScript string into a single-quoted Python literal with
 * standard backslash escaping. Suitable for short labels.
 */
export function pyStr(s: string): string {
  return JSON.stringify(s);
}

/**
 * Format a JS number as a Python float literal. We avoid scientific
 * notation for integer-ish values so the generated script reads
 * cleanly when copy-pasted into a notebook.
 */
export function pyNum(x: number, digits = 6): string {
  if (!Number.isFinite(x)) {
    if (Number.isNaN(x)) return 'float("nan")';
    return x > 0 ? 'float("inf")' : 'float("-inf")';
  }
  if (Number.isInteger(x)) return String(x);
  // Trim insignificant trailing zeros from a fixed-precision string.
  const s = x.toFixed(digits);
  return s.replace(/0+$/, '').replace(/\.$/, '.0');
}

/** Render a 1-D array of numbers as a Python list literal. */
export function pyList(values: ReadonlyArray<number>, digits = 6): string {
  return `[${values.map((v) => pyNum(v, digits)).join(', ')}]`;
}

/** Render a 2-D array of numbers as a nested Python list literal. */
export function pyMatrix(
  rows: ReadonlyArray<ReadonlyArray<number>>,
  digits = 6,
): string {
  if (rows.length === 0) return '[]';
  return `[\n${rows
    .map((r) => `    ${pyList(r, digits)},`)
    .join('\n')}\n]`;
}

/** Render a 1-D array of strings as a Python list literal. */
export function pyStrList(values: ReadonlyArray<string>): string {
  return `[${values.map((s) => pyStr(s)).join(', ')}]`;
}

/**
 * Common preamble shared by every emitter. Centralised so that future
 * additions (e.g. a `# Generated by …` banner with the chart id) only
 * need to be made in one place.
 */
export interface PythonHeaderOptions {
  /** Display title rendered in the docstring (Chinese OK). */
  title: string;
  /** Optional caption rendered after the title. */
  caption?: string;
  /** Optional one-line description of the chart shown above the figure. */
  description?: string;
}

export function pythonHeader(opts: PythonHeaderOptions): string {
  const { title, caption, description } = opts;
  const summary = [title, caption].filter(Boolean).join(' — ');
  const desc = description ?? `Reproduces "${title}" as a static matplotlib figure.`;
  return `"""\n${summary}\n\n${desc}\n\nGenerated by EEG-fNIRS Vector Figure Studio.\nRun: \`python ${slugifyForFilename(title)}.py\`\n"""\nimport matplotlib.pyplot as plt\nimport numpy as np\n`;
}

/**
 * Rough slugifier for the docstring's run-instruction line. Not used
 * for actual filenames (the chart author supplies those explicitly to
 * `downloadPythonFile`).
 */
export function slugifyForFilename(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48) || 'figure';
}

/**
 * Render a matplotlib `set_title` / `set_xlabel` / `set_ylabel` call
 * with a guard against empty strings so the emitted script doesn't
 * leak unwanted whitespace into the figure.
 */
export function pyAxisLabel(
  axisExpr: string,
  method: 'set_title' | 'set_xlabel' | 'set_ylabel' | 'suptitle',
  text: string,
  kwargs?: Record<string, string | number | boolean>,
): string {
  if (!text) return '';
  const trailing = kwargs
    ? ', ' +
      Object.entries(kwargs)
        .map(([k, v]) => `${k}=${typeof v === 'string' ? pyStr(v) : v}`)
        .join(', ')
    : '';
  return `${axisExpr}.${method}(${pyStr(text)}${trailing})\n`;
}
